---
- name: Installer paquets OCS Inventory Server
  ansible.builtin.apt:
    name:
      - ocsinventory-server
      - ocsinventory-reports
    state: present
    update_cache: yes

- name: S’assurer qu’Apache est démarré pour OCS
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
